Exercise 2 

In [13]:
import numpy as np
Student_details = np.array([
                            [78,85,90],
                            [45,60,55],
                            [88,92,95],
                            [30,40,35], 
                            [65,70,75]])
print(Student_details)
print(Student_details.shape)
print(Student_details.dtype)
print(Student_details.size)


[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
(5, 3)
int64
15


In [22]:
import numpy as np
Student_details = np.array([
                            [78,85,90],
                            [45,60,55],
                            [88,92,95],
                            [30,40,35], 
                            [65,70,75]])
print(Student_details[np.array([1])])
print(Student_details[np.array([2])])

print(Student_details[0,1])


[[45 60 55]]
[[88 92 95]]
85


calculating means and averages 

In [27]:
print(np.sum(Student_details, axis=0))

[306 347 350]
