you are managing the electronics section of a store, you need to track the sales of **3 products**: Headphones, Smartwatches,and speakers over **4 days**(Monday to thursday).

o Row 0: Headphones
o Row 1: Smartwatches
o Row 2: Speakers 


task creating array 

In [9]:
import numpy as np
cost_price= np.array([1500,3000,5000])
print(cost_price)
daily_sales = np.array([[10,15,8,3],
                        [5,7,4,6],
                        [2,3,2,4]])
print(daily_sales.shape)

[1500 3000 5000]
(3, 4)


In [15]:
import numpy as np
daily_sales = np.array([[10,15,8,5],
                        [5,7,4,6],
                        [2,3,2,4]])
print(daily_sales.shape)


(3, 4)


task 2.1  add 2 for array

In [21]:
import numpy as np
cost_price= np.array([1500,3000,5000])
print(cost_price)
daily_sales = np.array([[10,15,8,5],
                        [5,7,4,6],
                        [2,3,2,4]])
print(daily_sales + 2)
print(daily_sales.shape)
print(cost_price.reshape(-1, 1) * daily_sales)
print(cost_price.shape)

[1500 3000 5000]
[[12 17 10  7]
 [ 7  9  6  8]
 [ 4  5  4  6]]
(3, 4)
[[15000 22500 12000  7500]
 [15000 21000 12000 18000]
 [10000 15000 10000 20000]]
(3,)


In [ ]:
Task 3.1
Access the sales data for smartwatches for all 4 daily_sales

In [23]:
import numpy as np
daily_sales = np.array([[10,15,8,5],
                        [5,7,4,6],
                        [2,3,2,4]])
print(daily_sales[1])

[5 7 4 6]


Task 3.2 
Access the sales data for all products for the first two days

In [38]:
import numpy as np
daily_sales = np.array([[10,15,8,5],
                        [5,7,4,6],
                        [2,3,2,4]])
print(daily_sales[0,0],daily_sales[0,1])
print(daily_sales[1,0],daily_sales[1,1])
print(daily_sales[2,0],daily_sales[2,1])

10 15
5 7
2 3


exercise 2


In [6]:
import numpy as np
arr=np.array([[1,2,3],
             [4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [8]:
print(np.sum (arr))

21


In [10]:
print(np.sum(arr, axis=0))
print(np.sum(arr, axis=1))

[5 7 9]
[ 6 15]


where in numpy 

In [11]:
arr= np.array((10,-5,20,-3,15))

In [12]:
result= np.where(arr<0, 0, arr)
print(result)

[10  0 20  0 15]


In [13]:
arr=np.array([1,2,3,4,5])


In [14]:
result= np.where(arr%2 !=0,-1, arr)
print(result)

[-1  2 -1  4 -1]


In [16]:
marks = np.array([45, 78,32, 90, 55])

In [17]:
status = np.where(marks>=50,1,0)
print(status)

[0 1 0 1 1]


In [18]:
data= np.array([10,20,30,40,50])

In [19]:
mean_val=np.mean(data)
result= np.where(data>mean_val,mean_val, data)
print(result)

[10. 20. 30. 30. 30.]


Applying (where) condition in 2D Array  

In [22]:
mat=np.array([
    [10,60,30],
    [80,20,90]])