In [5]:
import numpy as np
mat = np.array([[2,3,1],[4,2,5]])
print(mat)

[[2 3 1]
 [4 2 5]]


In [8]:
arr=np.array([1.2,2.5,3.7])
arr_int=arr.astype(int)
print(arr_int)

[1 2 3]


In [9]:
arr=np.array([10,20,30,40])
print(arr[2])
print(arr[-1])

30
40


In [6]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [16]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [17]:
print(arr[1:3])
print(arr[:2])
print(arr[::2])

[20 30]
[10 20]
[10 30]


In [19]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat[0,1])
print(mat[1])

2
[4 5 6]


In [20]:
print(mat[:,1])

[2 5 8]


In [26]:
a = np.array([1,2,3])
b = a.copy()
b[0]=10
print(a)
print(b)

[1 2 3]
[10  2  3]


In [27]:
a = np.array([1,2,3])
b = a #this logic is not safe
b[0]=10
print(a)

[10  2  3]


In [28]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [29]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [32]:


print(a+10)
print(a*2)

[11 12 13]
[2 4 6]


In [33]:
arr=np.array([1,4,9,16])

print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
7.5
30
5.678908345800274


In [34]:
arr=np.array([10,20,30,40,50])
print(arr>25)
print(arr[arr>25])

[False False  True  True  True]
[30 40 50]


In [35]:
#numpy automatically expands smaller arrays

In [36]:
arr=np.array([1,2,3,4])
print(arr+10)

[11 12 13 14]


In [37]:
mat=np.array([[1,2,3],
              [4,5,6]])
print(mat+10)

[[11 12 13]
 [14 15 16]]


In [ ]:
row=np.array([1,2,3])
print(mat+row)

[[2 4 6]
 [5 7 9]]


Matrix Multiplication

In [ ]:
A= np.array([[1,2],
             [3,4]])
B= np.array([[5,6],
             [7,8]])
print(np.dot(A,B))


[[19 22]
 [43 50]]


In [43]:
print(A.T) #transpose

[[1 3]
 [2 4]]


Random Module

In [44]:
np.random.rand(5)

array([0.81473593, 0.76245028, 0.67842544, 0.28188868, 0.35986468])

In [45]:
np.random.rand(3,3)  

array([[0.60625589, 0.75331295, 0.14090332],
       [0.55652931, 0.17808617, 0.87903139],
       [0.8985306 , 0.43495133, 0.34125561]])

In [46]:
np.random.randint(1,100,10)

array([13, 23, 94, 33, 36, 94, 48, 64, 44, 50], dtype=int32)

Reshapping Arrays


In [48]:
arr=np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

1
(4,)
4
int64
