<a href="https://colab.research.google.com/github/hairishbabucse273/CSE-237_Exercise_Collection/blob/main/CSE273_Exercise03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task A1 — Create the Array Using Random Values

In [ ]:
import numpy as np

# Random electricity usage between 120 and 650
electricity = np.random.randint(120, 651, size=(4, 7))

print(electricity)


[[265 392 239 333 639 556 346]
 [379 330 604 229 363 395 236]
 [288 398 311 405 543 131 606]
 [550 612 187 413 579 517 149]]


Task A2 — Array Attributes

In [ ]:
print("Shape:", electricity.shape)
print("Number of dimensions:", electricity.ndim)
print("Total elements:", electricity.size)
print("Data type:", electricity.dtype)


Shape: (4, 7)
Number of dimensions: 2
Total elements: 28
Data type: int64


Task B1 — Hostel-Wise Metrics

In [ ]:
# Average usage per hostel (row-wise)
hostel_avg = np.mean(electricity, axis=1)
print("Average per hostel:", hostel_avg)

# Maximum usage per hostel
hostel_max = np.max(electricity, axis=1)
print("Maximum per hostel:", hostel_max)

# Hostel with highest average usage
highest_avg_hostel = np.argmax(hostel_avg) + 1
print("Hostel with highest average usage: H", highest_avg_hostel)


Average per hostel: [395.71428571 362.28571429 383.14285714 429.57142857]
Maximum per hostel: [639 604 606 612]
Hostel with highest average usage: H 4


Task B2 — Day-Wise Metrics

In [ ]:
# Total usage per day (column-wise)
daily_total = np.sum(electricity, axis=0)
print("Total usage per day:", daily_total)

# Day with highest total consumption
highest_day = np.argmax(daily_total)
print("Day index with highest consumption:", highest_day)


Total usage per day: [1482 1732 1341 1380 2124 1599 1337]
Day index with highest consumption: 4


Task C1 — Apply 20% Surcharge (Usage > 550) Using np.where

In [ ]:
penalized_usage = np.where(electricity > 550,
                           electricity * 1.20,
                           electricity)

print("Penalized usage:\n", penalized_usage)


Penalized usage:
 [[265.  392.  239.  333.  766.8 667.2 346. ]
 [379.  330.  724.8 229.  363.  395.  236. ]
 [288.  398.  311.  405.  543.  131.  727.2]
 [550.  734.4 187.  413.  694.8 517.  149. ]]


Task D1 — Above/Below Hostel Weekly Average (Broadcasting)

In [ ]:
# Weekly average per hostel (shape: 4,)
weekly_avg = np.mean(electricity, axis=1)

# Broadcasting comparison to (4,7)
above_avg_matrix = electricity > weekly_avg[:, np.newaxis]

print("Above hostel average matrix:\n", above_avg_matrix)


Above hostel average matrix:
 [[False False False False  True  True False]
 [ True False  True False  True  True False]
 [False  True False  True  True False  True]
 [ True  True False False  True  True False]]


Task E1 — Reshape to Single Row (1 × 28)

In [ ]:
single_row = electricity.reshape(1, 28)
print("Reshaped (1x28):\n", single_row)


Task E2 — Reshape to (2 × 14)

In [ ]:
reshaped_2x14 = electricity.reshape(2, 14)
print("Reshaped (2x14):\n", reshaped_2x14)


Task F1 — Copy & View

In [ ]:
ref_backup = electricity            # View (reference)
safe_backup = electricity.copy()   # Independent copy

print("Before modification:\n", electricity)

# Modify original
electricity[0, 0] = 999

print("After modification - Original:\n", electricity)
print("Reference Backup:\n", ref_backup)
print("Safe Backup:\n", safe_backup)


Before modification:
 [[265 392 239 333 639 556 346]
 [379 330 604 229 363 395 236]
 [288 398 311 405 543 131 606]
 [550 612 187 413 579 517 149]]
After modification - Original:
 [[999 392 239 333 639 556 346]
 [379 330 604 229 363 395 236]
 [288 398 311 405 543 131 606]
 [550 612 187 413 579 517 149]]
Reference Backup:
 [[999 392 239 333 639 556 346]
 [379 330 604 229 363 395 236]
 [288 398 311 405 543 131 606]
 [550 612 187 413 579 517 149]]
Safe Backup:
 [[265 392 239 333 639 556 346]
 [379 330 604 229 363 395 236]
 [288 398 311 405 543 131 606]
 [550 612 187 413 579 517 149]]
