<a href="https://colab.research.google.com/github/hairishbabucse273/CSE-237_Exercise_Collection/blob/main/CSE273_Exercise02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task — Create 2D Array (5 Students × 3 Subjects)

In [ ]:
import numpy as np

# Rows = Students, Columns = Subjects
student_marks = np.array([
    [78, 85, 90],
    [45, 60, 55],
    [88, 92, 95],
    [30, 40, 35],
    [65, 70, 75]
])

print(student_marks)


[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


Task A1 — Metadata Discovery

In [ ]:
print("Shape of array:", student_marks.shape)
print("Total elements:", student_marks.size)
print("Data type:", student_marks.dtype)


Task A2 — Data Indexing & Slicing

In [ ]:
# All marks for 2nd student
print("2nd student marks:", student_marks[1])

# All students' marks in 3rd subject
print("Subject 3 marks for all students:", student_marks[:, 2])

# Specific mark: Student 1, Subject 2
print("Student 1, Subject 2:", student_marks[0, 1])


Task B1 — Means and Averages (Using axis)

In [ ]:
# Average marks of each student (row-wise)
student_avg = np.mean(student_marks, axis=1)
print("Student averages:", student_avg)

# Average marks of each subject (column-wise)
subject_avg = np.mean(student_marks, axis=0)
print("Subject averages:", subject_avg)


Task B2 — Filtering Top Performers (Average ≥ 80)

In [ ]:
top_performers = student_avg >= 80
print("Top performers (mask):", top_performers)
print("Their averages:", student_avg[top_performers])


Task B3 — Global Adjustment (Add 5 Grace Marks)

In [ ]:
marks_with_grace = student_marks + 5
print("Marks after grace:\n", marks_with_grace)


Task C1 — Pass/Fail Mapping (Pass ≥ 50)

In [ ]:
pass_fail_matrix = (marks_with_grace >= 50).astype(int)
print("Pass/Fail matrix:\n", pass_fail_matrix)


Task C2 — Data Cleaning (Marks < 40 → 0)

In [ ]:
cleaned_marks = marks_with_grace.copy()
cleaned_marks[cleaned_marks < 40] = 0
print("Cleaned marks:\n", cleaned_marks)

# Recalculate averages
new_avg = np.mean(cleaned_marks, axis=1)
print("New averages:", new_avg)


Task D1 — Grade Allocation Using NumPy Conditions

In [ ]:
conditions = [
    new_avg >= 85,
    new_avg >= 70,
    new_avg >= 50,
    new_avg < 50
]

grade_choices = ['A', 'B', 'C', 'No Grade']
score_choices = [10, 8, 6, 0]

student_grades = np.select(conditions, grade_choices)
student_scores = np.select(conditions, score_choices)

print("Grades:", student_grades)
print("Scores:", student_scores)


Task E1 — Copy vs View Demonstration

In [ ]:
backup_copy = cleaned_marks.copy()  # Independent copy
backup_view = cleaned_marks         # Reference

print("Before modification:\n", cleaned_marks)

# Modify original array
cleaned_marks[0, 0] = 0

print("After modification - Original:\n", cleaned_marks)
print("Backup Copy:\n", backup_copy)
print("Backup View:\n", backup_view)
