<a href="https://colab.research.google.com/github/hairishbabucse273/CSE-237_Exercise_Collection/blob/main/cse273_exercise01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
mat = np.array([[2,3,1],
               [4,5,6]])
print(mat)

[[2 3 1]
 [4 5 6]]


In [ ]:
arr = np.array([1.2,2.5,3.7])
arr_int = arr.astype(int)
print(arr_int)

[1 2 3]


In [ ]:
arr = np.array([10,20,30,40])
print(arr[2])
print(arr[-1])

30
40


In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [ ]:
print(arr[1:3])
print(arr[:2])
print(arr[::2])

[20 30]
[10 20]
[10 30]


In [ ]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(mat[0,1])
print(mat[1])

2
[4 5 6]


In [ ]:
print(mat[:, 1])

[2 5 8]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 10
print(a)
print(b)

[1 2 3]
[10  2  3]


In [ ]:
a = 5
b = 1
print(a + b)
print(a - b)
print(a * b)
print(a / b)

6
4
5
5.0


In [ ]:
print(a + 10)
print(a * 2)

15
10


In [ ]:
arr = np.array([1,4,9,16])
print(np.sqrt(arr))
print(np.log(arr))
print(np.exp(arr))
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.sum(arr))
print(np.std(arr))

[1. 2. 3. 4.]
[0.         1.38629436 2.19722458 2.77258872]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
16
1
7.5
30
5.678908345800274


In [ ]:
arr = np.array([10,20,30,40,50])
print(arr > 25)
print(arr[arr > 25])

[False False  True  True  True]
[30 40 50]


In [ ]:
np.random.rand(5)

array([0.46680527, 0.63411145, 0.75383567, 0.481768  , 0.35007013])

In [ ]:
np.random.rand(3,3)

array([[3.49361868e-04, 6.82692048e-01, 7.00823261e-01],
       [3.31404568e-01, 7.35438459e-02, 1.76251738e-01],
       [3.18489020e-01, 2.88426561e-01, 9.78982976e-01]])

In [ ]:
np.random.randint(1,101,10)

array([  1,  53,  97,  83,  66, 100,  81,  18,  27,  42])

In [ ]:
A = np.array([[1,2],
              [3,4],])
B = np.array([[5,6],
              [7,8]])
print(np.dot(A,B))
print(A.T)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [ ]:
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

1
(4,)
4
int64


In [ ]:
arr = np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
### You are managing the electronics section of a store. Need to track the sales of 3 products : Headphones, SmartPhones, and Speakers over 4 Days (Mon to Thu).
### Row : Headphones
### Row : SmartPhones
### Row : Speakers

In [ ]:
import numpy as np
cost_price = np.array([1500,3000,5000])
print(cost_price)
daily_sales = np.array([[10,15,8,7],
                       [5,7,4,6],
                       [2,3,2,4]])
print(daily_sales + 2)
print(daily_sales.shape)
print(daily_sales[:, 0:2])
random_values = np.random.rand(5)




[1500 3000 5000]
[[12 17 10  9]
 [ 7  9  6  8]
 [ 4  5  4  6]]
(3, 4)
[[10 15]
 [ 5  7]
 [ 2  3]]
